### ACSVM ###

if(BUILD_CLIENT OR BUILD_SERVER)
  lib_buildgen(
    LIBRARY ACSVM
    PARAMS "-DCMAKE_DEBUG_POSTFIX=d"
           "-DACSVM_ENABLE_UTIL=OFF"
           "-DACSVM_ENABLE_EXEC=OFF"
           "-DACSVM_SHARED=OFF"
           "-DACSVM_INSTALL_API=ON"
           "-DACSVM_INSTALL_LIB=ON"
           "-DACSVM_NOFLAGS=ON")
  lib_build(LIBRARY ACSVM)

  add_library(ACSVM STATIC IMPORTED GLOBAL)
  set_target_properties(ACSVM PROPERTIES
    IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/local/lib/ACSVM${libsuffix}"
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/ACSVM/ACSVM"
  )
endif()
