name: macOS

on: [push, pull_request]

jobs:
  pre_job:
    name: Build Preparation
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check_skip.outputs.should_skip }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Check for build skip
        id: check_skip
        run: bash ci/check-skip.sh
  build:
    name: Build
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: macos-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Prepare build
      run: bash ci/macos-buildgen.sh
    - name: Run build
      run: cmake --build ./build/
    - name: Create DMG
      run: brew install create-dmg |
          create-dmg ./build/Release/ ./build/Release/odamex.dmg --background ./media/macinstaller-background.png
    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: Odamex-MacOS
        path: 'build/Release/odamex.dmg'